import QueryProviders from '@/providers/QueryProviders'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/providers/ReduxProvider'
import Sidebar from '@/components/Sidebar'
import Hamburger from '@/components/Hamburger'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProviders>
      <body className={inter.className}>
        <ReduxProvider>
          <>
          <Hamburger/>
          <Sidebar/>
        {children}
          </>
        </ReduxProvider>
        </body>
      </QueryProviders>
    </html>
  )
}
